=== Homoki-Ugyvedi-Iroda/HotDocsHPWordAddin/HotDocs_HP_WordAddIn/Resources/customXMLContracts.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.homoki.net/uri/customXMLcontracts/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root">
    <xs:annotation>
      <xs:documentation>szerződés típusa/tárgya = dc:subject, dc:keywords, dc:description, dc:contentstatus, szerződés címe = dc:title, dc:date = Date of last signature or usual date used for dating, szerző = Author (Word) = dc:creator</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="HotDocsReferences" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="ClientName" minOccurs="0" />
                    <xs:element type="xs:string" name="ClientAddress"  minOccurs="0" />
                    <xs:element type="xs:string" name="ClientObligatoryMiscInformation"  minOccurs="0" />
                    <xs:element type="xs:string" name="ClientRegisterFullData"  minOccurs="0" />
                    <xs:element type="xs:string" name="ClientRegisterName"  minOccurs="0" />
                    <xs:element type="xs:string" name="ClientRegistrationIdentifier"  minOccurs="0" />
                    <xs:element type="xs:string" name="ClientSignatureDate" minOccurs="0" />
                    <xs:element type="xs:string" name="ClientSignaturePlace" minOccurs="0" />
                    <xs:element type="xs:string" name="ClientTaxNumberHun" minOccurs="0" />
                    <xs:element type="xs:string" name="ClientTaxNumber" minOccurs="0" />                    
                    <xs:element type="xs:string" name="PartnerName" minOccurs="0" />
                    <xs:element type="xs:string" name="PartnerAddress"  minOccurs="0" />
                    <xs:element type="xs:string" name="PartnerObligatoryMiscInformation"  minOccurs="0" />
                    <xs:element type="xs:string" name="PartnerRegisterFullData"  minOccurs="0" />
                    <xs:element type="xs:string" name="PartnerRegisterName"  minOccurs="0" />
                    <xs:element type="xs:string" name="PartnerRegistrationIdentifier"  minOccurs="0" />
                    <xs:element type="xs:string" name="PartnerSignatureDate" minOccurs="0" />
                    <xs:element type="xs:string" name="PartnerSignaturePlace" minOccurs="0" />
                    <xs:element type="xs:string" name="PartnerTaxNumber" minOccurs="0" />
                    <xs:element type="xs:string" name="PartnerTaxNumberHun" minOccurs="0" />
                    <xs:element type="xs:string" name="FeeCurrency" minOccurs="0" />
                    <xs:element type="xs:string" name="ContractTitle" minOccurs="0" />
                    <xs:element type="xs:string" name="ContractTitleToModifyName" minOccurs="0" />
                    <xs:element type="xs:string" name="PartnerRepresentedBy" minOccurs="0" />
                    <xs:element type="xs:string" name="ClientRepresentedBy" minOccurs="0" />
                    <xs:element type="xs:string" name="AlperesLevelezesiCime" minOccurs="0" />
                    <xs:element type="xs:string" name="AlperesNeve" minOccurs="0" />
                    <xs:element type="xs:string" name="BirosagNeve" minOccurs="0" />
                    <xs:element type="xs:string" name="EljaroUgyvedNeve" minOccurs="0" />
                    <xs:element type="xs:string" name="FelperesLevelezesiCime" minOccurs="0" />
                    <xs:element type="xs:string" name="FelperesNeve" minOccurs="0" />
                    <xs:element type="xs:string" name="JogiKepviseloNeve" minOccurs="0" />
                    <xs:element type="xs:string" name="KovetelesErteke" minOccurs="0" />
                    <xs:element type="xs:string" name="KozigazgatasiHatarozat" minOccurs="0" />
                    <xs:element type="xs:string" name="PerTargya" minOccurs="0" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
        <xs:element name="client" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name" />
                    <xs:element type="xs:string" name="role"  minOccurs="0" />
                    <xs:element type="xs:string" name="address"  minOccurs="0" />
                    <xs:element type="xs:string" name="taxnumber"  minOccurs="0" />
                    <xs:element type="xs:string" name="otherIDdata"  minOccurs="0" />
                    <xs:element type="xs:string" name="contractID"  minOccurs="0" />
                    <xs:element type="xs:string" name="caseOrProcessID" minOccurs="0" />
                    <xs:element type="xs:string" name="commitmentNature" minOccurs="0" />
                    <xs:element type="xs:string" name="commitmentEnd" minOccurs="0" />
                    <xs:element type="xs:string" name="placeOfSignature" minOccurs="0" />
                    <xs:element type="xs:string" name="dateOfSignature" minOccurs="0" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
        <xs:element name="clientsPartner" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name" />
                    <xs:element type="xs:string" name="role"  minOccurs="0" />
                    <xs:element type="xs:string" name="address"  minOccurs="0" />
                    <xs:element type="xs:string" name="taxnumber"  minOccurs="0" />
                    <xs:element type="xs:string" name="otherIDdata"  minOccurs="0" />
                    <xs:element type="xs:string" name="contractID"  minOccurs="0" />
                    <xs:element type="xs:string" name="caseOrProcessID" minOccurs="0" />
                    <xs:element type="xs:string" name="commitmentNature" minOccurs="0" />
                    <xs:element type="xs:string" name="commitmentEnd" minOccurs="0" />
                    <xs:element type="xs:string" name="placeOfSignature" minOccurs="0" />
                    <xs:element type="xs:string" name="dateOfSignature" minOccurs="0" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
        <xs:element name="thirdParty" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name" />
                    <xs:element type="xs:string" name="role"  minOccurs="0" />
                    <xs:element type="xs:string" name="address"  minOccurs="0" />
                    <xs:element type="xs:string" name="taxnumber"  minOccurs="0" />
                    <xs:element type="xs:string" name="otherIDdata"  minOccurs="0" />
                    <xs:element type="xs:string" name="contractID"  minOccurs="0" />
                    <xs:element type="xs:string" name="caseOrProcessID" minOccurs="0" />
                    <xs:element type="xs:string" name="commitmentNature" minOccurs="0" />
                    <xs:element type="xs:string" name="commitmentEnd" minOccurs="0" />
                    <xs:element type="xs:string" name="placeOfSignature" minOccurs="0" />
                    <xs:element type="xs:string" name="dateOfSignature" minOccurs="0" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>         
        <xs:element type="xs:string" name="frontPart" minOccurs="0" />
        <xs:element type="xs:string" name="bodyPart" minOccurs="0" />
        <xs:element type="xs:string" name="backPart" minOccurs="0" />
        <xs:element type="xs:string" name="attachmentList" minOccurs="0" />
        <xs:element type="xs:string" name="signatureBlock" minOccurs="0" />
        <xs:element type="xs:string" name="definitionBlock" minOccurs="0" />
        <xs:element name="contractModified" minOccurs="0" >
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="lastSignatureDate"  minOccurs="0" />
              <xs:element type="xs:string" name="effectivityDate"  minOccurs="0" />
              <xs:element type="xs:string" name="ID"  minOccurs="0" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:string" name="neutralContractID" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="term"  minOccurs="0" >
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="begin" minOccurs="0" />
                <xs:element type="xs:string" name="end" minOccurs="0" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="objectofContract" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name" minOccurs="0" />
              <xs:element type="xs:string" name="ID" minOccurs="0" />
              <xs:element type="xs:string" name="address" minOccurs="0" />
              <xs:element type="xs:string" name="description" minOccurs="0" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Homoki-Ugyvedi-Iroda/HotDocsHPWordAddin/HotDocs_HP_WordAddIn/Resources/blank_customXMLContracts.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns="http://www.homoki.net/uri/customXMLcontracts/" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
<!--xsi:schemaLocation="http://www.homoki.net/uri/customXMLcontracts/ customXMLContracts.xsd"-->
<HotDocsReferences>
<ClientName/>
<ClientAddress/>
<ClientObligatoryMiscInformation/>
<ClientRegisterFullData/>
<ClientRegisterName/>
<ClientRegistrationIdentifier/>
<ClientSignatureDate/>
<ClientSignaturePlace/>
<ClientTaxNumberHun/>
<ClientTaxNumber/>
<PartnerName/>
<PartnerAddress/>
<PartnerObligatoryMiscInformation/>
<PartnerRegisterFullData/>
<PartnerRegisterName/>
<PartnerRegistrationIdentifier/>
<PartnerSignatureDate/>
<PartnerSignaturePlace/>
<PartnerTaxNumber/>
<FeeCurrency/>
<ContractTitle/>
<ContractTitleToModifyName/>
<PartnerRepresentedBy/>
<ClientRepresentedBy/>
<!--<AlperesLevelezesiCime/>
<AlperesNeve/>
<BirosagNeve/>
<EljaroUgyvedNeve/>
<FelperesLevelezesiCime/>
<FelperesNeve/>
<JogiKepviseloNeve/>
<KovetelesErteke/>
<KozigazgatasiHatarozat/>
<PerTargya/>-->
</HotDocsReferences>
<client>
<name/>
<role/>
<address/>
<taxnumber/>
<otherIDdata/>
<contractID/>
<caseOrProcessID/>
<commitmentNature/>
<commitmentEnd/>
<placeOfSignature/>
<dateOfSignature/>
</client>
<clientsPartner>
<name/>
<role/>
<address/>
<taxnumber/>
<otherIDdata/>
<contractID/>
<caseOrProcessID/>
<commitmentNature/>
<commitmentEnd/>
<placeOfSignature/>
<dateOfSignature/>
</clientsPartner>
<thirdParty>
<name/>
<role/>
<address/>
<taxnumber/>
<otherIDdata/>
<contractID/>
<caseOrProcessID/>
<commitmentNature/>
<commitmentEnd/>
<placeOfSignature/>
<dateOfSignature/>
</thirdParty>
<frontPart/>
<bodyPart/>
<backPart/>
<attachmentList/>
<signatureBlock/>
<definitionBlock/>
<contractModified>
<name/>
<lastSignatureDate/>
<effectivityDate/>
<ID/>
</contractModified>
<neutralContractID/>
<term>
<begin/>
<end/>
</term>
<objectofContract>
<name/>
<ID/>
<address/>
<description/>
</objectofContract>
</root>
